/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp } from 'firebase/app';
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, User } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

// Construct the operational Firebase configuration.
// It checks environment variables (VITE_ prefix is required for client-side configuration in Vite) First,
// and falls back to the default config JSON generated by AI Studio.
const metaEnv = (import.meta as any).env || {};

// We use import.meta.glob with a wildcard so that if the file doesn't exist, 
// Vite won't throw a compile-time resolution error.
const configFiles = (import.meta as any).glob('../../firebase-applet-config*.json', { eager: true });
const configKeys = Object.keys(configFiles);
const firebaseConfigDefault = configKeys.length > 0 
  ? ((configFiles[configKeys[0]] as any).default || {}) 
  : {};

const firebaseConfig = {
  apiKey: metaEnv.VITE_FIREBASE_API_KEY || firebaseConfigDefault.apiKey || "",
  authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfigDefault.authDomain || "",
  projectId: metaEnv.VITE_FIREBASE_PROJECT_ID || firebaseConfigDefault.projectId || "",
  storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET || firebaseConfigDefault.storageBucket || "",
  messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID || firebaseConfigDefault.messagingSenderId || "",
  appId: metaEnv.VITE_FIREBASE_APP_ID || firebaseConfigDefault.appId || "",
  measurementId: metaEnv.VITE_FIREBASE_MEASUREMENT_ID || firebaseConfigDefault.measurementId || ""
};

// OAuth 2.0 Web client ID (Google Cloud Console -> APIs & Services -> Credentials).
// Required for silent token refresh via Google Identity Services.
const GOOGLE_CLIENT_ID = metaEnv.VITE_GOOGLE_CLIENT_ID || firebaseConfigDefault.clientId || "";
const OAUTH_SCOPES = "https://www.googleapis.com/auth/documents https://www.googleapis.com/auth/drive";

let app: any = null;
let auth: any = null;
let db: any = null;
let provider: any = null;
let initError: Error | null = null;

try {
  const isKeyEmpty = !firebaseConfig.apiKey || firebaseConfig.apiKey.trim() === "";
  const isKeyPlaceholder = firebaseConfig.apiKey.includes("YOUR_") || firebaseConfig.apiKey === "null" || firebaseConfig.apiKey === "undefined";
  
  if (isKeyEmpty || isKeyPlaceholder) {
    throw new Error('Firebase apiKey is missing or not configured. To enable Google Sign-In, please use "Set up Firebase" in the AI Studio UI or configure your Firebase environment variables.');
  }

  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  
  // Initializespecifically with the user's allocated Firestore Database ID if configured
  if (firebaseConfigDefault.firestoreDatabaseId) {
    db = getFirestore(app, firebaseConfigDefault.firestoreDatabaseId);
  } else {
    db = getFirestore(app);
  }

  provider = new GoogleAuthProvider();
  // Request Google Docs and Google Drive scopes
  provider.addScope('https://www.googleapis.com/auth/documents');
  provider.addScope('https://www.googleapis.com/auth/drive');
} catch (err: any) {
  console.warn('Firebase or Auth initialization bypassed:', err.message || err);
  initError = err;
}

export { auth, db };

// Flag to indicate if we are in the middle of a sign-in flow.
let isSigningIn = false;
// Cache the access token in memory or load from localStorage
let cachedAccessToken: string | null = (() => {
  try {
    return localStorage.getItem('gdocs_access_token');
  } catch {
    return null;
  }
})();

// When the cached access token expires (epoch ms). Google access tokens last ~1h.
let tokenExpiryMs: number | null = (() => {
  try {
    const v = localStorage.getItem('gdocs_token_expiry');
    return v ? Number(v) : null;
  } catch {
    return null;
  }
})();

function persistToken(token: string, expiresInSec: number) {
  cachedAccessToken = token;
  tokenExpiryMs = Date.now() + expiresInSec * 1000;
  try {
    localStorage.setItem('gdocs_access_token', token);
    localStorage.setItem('gdocs_token_expiry', String(tokenExpiryMs));
  } catch (e) {
    console.warn('Failed to persist access token:', e);
  }
}

// --- Silent token refresh via Google Identity Services (GIS) ---
let gisScriptPromise: Promise<void> | null = null;
let gisTokenClient: any = null;
let pendingResolve: ((t: string | null) => void) | null = null;
let pendingRefresh: Promise<string | null> | null = null;

function loadGisScript(): Promise<void> {
  if (gisScriptPromise) return gisScriptPromise;
  gisScriptPromise = new Promise<void>((resolve, reject) => {
    if ((window as any).google?.accounts?.oauth2) return resolve();
    const s = document.createElement('script');
    s.src = 'https://accounts.google.com/gsi/client';
    s.async = true;
    s.defer = true;
    s.onload = () => resolve();
    s.onerror = () => reject(new Error('Failed to load Google Identity Services script'));
    document.head.appendChild(s);
  });
  return gisScriptPromise;
}

async function ensureTokenClient(): Promise<any> {
  if (!GOOGLE_CLIENT_ID) {
    throw new Error('VITE_GOOGLE_CLIENT_ID is not configured; cannot silently refresh the Google access token.');
  }
  await loadGisScript();
  if (!gisTokenClient) {
    gisTokenClient = (window as any).google.accounts.oauth2.initTokenClient({
      client_id: GOOGLE_CLIENT_ID,
      scope: OAUTH_SCOPES,
      callback: (resp: any) => {
        const resolve = pendingResolve;
        pendingResolve = null;
        if (resp.error || !resp.access_token) {
          console.error('[Auth] Silent token refresh response error:', resp.error || 'no access_token');
          if (resolve) resolve(null);
          return;
        }
        persistToken(resp.access_token, Number(resp.expires_in) || 3600);
        if (resolve) resolve(cachedAccessToken);
      },
    });
  }
  return gisTokenClient;
}

// Silently obtain a fresh access token. No popup if the user's Google session is
// active and consent was already granted; resolves null if interaction is required.
export const refreshAccessTokenSilently = async (): Promise<string | null> => {
  if (pendingRefresh) return pendingRefresh;
  pendingRefresh = (async () => {
    try {
      const client = await ensureTokenClient();
      return await new Promise<string | null>((resolve) => {
        pendingResolve = resolve;
        client.requestAccessToken({ prompt: '' });
      });
    } catch (e) {
      console.error('[Auth] Silent token refresh failed:', e);
      return null;
    }
  })().finally(() => {
    pendingRefresh = null;
  });
  return pendingRefresh;
};

// Return a token guaranteed fresh for the next few minutes, refreshing if needed.
export const getValidAccessToken = async (): Promise<string | null> => {
  const SKEW_MS = 5 * 60 * 1000;
  if (cachedAccessToken && tokenExpiryMs && Date.now() < tokenExpiryMs - SKEW_MS) {
    return cachedAccessToken;
  }
  const refreshed = await refreshAccessTokenSilently();
  return refreshed || cachedAccessToken;
};

// Initialize auth state listener. Call this on app load.
export const initAuth = (
  onAuthSuccess?: (user: User, token: string) => void,
  onAuthFailure?: () => void
) => {
  if (!auth || initError) {
    if (onAuthFailure) {
      setTimeout(() => onAuthFailure(), 0);
    }
    return () => {}; // return dummy unsubscriber
  }

  return onAuthStateChanged(auth, async (user: User | null) => {
    if (user) {
      // Use the cached token if still valid; otherwise silently refresh via GIS so a
      // page reload after the ~1h token expiry doesn't force a manual sign-in.
      const token = await getValidAccessToken();

      if (token) {
        if (onAuthSuccess) onAuthSuccess(user, token);
      } else if (!isSigningIn) {
        if (onAuthFailure) onAuthFailure();
      }
    } else {
      cachedAccessToken = null;
      try {
        localStorage.removeItem('gdocs_access_token');
      } catch {}
      if (onAuthFailure) onAuthFailure();
    }
  });
};

// Must be called from a button click or user interaction
export const googleSignIn = async (): Promise<{ user: User; accessToken: string } | null> => {
  if (!auth || initError) {
    const errorMsg = initError ? initError.message : 'Firebase Auth is not configured. To make Google Sign-In work, click "Set up Firebase" in AI Studio or check your VITE_FIREBASE_API_KEY environment variable.';
    throw new Error(errorMsg);
  }
  try {
    isSigningIn = true;
    const result = await signInWithPopup(auth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Failed to get access token from Firebase Auth');
    }

    // Firebase doesn't surface expires_in; Google access tokens are ~1h, so assume 3600s.
    persistToken(credential.accessToken, 3600);
    return { user: result.user, accessToken: cachedAccessToken! };
  } catch (error: any) {
    console.error('Sign in error:', error);
    throw error;
  } finally {
    isSigningIn = false;
  }
};

export const getAccessToken = async (): Promise<string | null> => {
  if (!cachedAccessToken) {
    try {
      cachedAccessToken = localStorage.getItem('gdocs_access_token');
    } catch {}
  }
  return cachedAccessToken;
};

export const logout = async () => {
  try {
    localStorage.removeItem('gdocs_access_token');
    localStorage.removeItem('gdocs_token_expiry');
  } catch {}
  cachedAccessToken = null;
  tokenExpiryMs = null;
  if (!auth) {
    return;
  }
  await auth.signOut();
};

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

export interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId?: string | null;
    email?: string | null;
    emailVerified?: boolean | null;
    isAnonymous?: boolean | null;
    tenantId?: string | null;
  }
}

export function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: auth?.currentUser?.uid || null,
      email: auth?.currentUser?.email || null,
      emailVerified: auth?.currentUser?.emailVerified || null,
      isAnonymous: auth?.currentUser?.isAnonymous || null,
      tenantId: auth?.currentUser?.tenantId || null
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}
