/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp } from 'firebase/app';
import { getAuth, signInWithPopup, GoogleAuthProvider, onAuthStateChanged, User } from 'firebase/auth';

// Construct the operational Firebase configuration.
// It checks environment variables (VITE_ prefix is required for client-side configuration in Vite) First,
// and falls back to the default config JSON generated by AI Studio.
const metaEnv = (import.meta as any).env || {};

// We use import.meta.glob with a wildcard so that if the file doesn't exist, 
// Vite won't throw a compile-time resolution error.
const configFiles = (import.meta as any).glob('../../firebase-applet-config*.json', { eager: true });
const configKeys = Object.keys(configFiles);
const firebaseConfigDefault = configKeys.length > 0 
  ? ((configFiles[configKeys[0]] as any).default || {}) 
  : {};

const firebaseConfig = {
  apiKey: metaEnv.VITE_FIREBASE_API_KEY || firebaseConfigDefault.apiKey || "",
  authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN || firebaseConfigDefault.authDomain || "",
  projectId: metaEnv.VITE_FIREBASE_PROJECT_ID || firebaseConfigDefault.projectId || "",
  storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET || firebaseConfigDefault.storageBucket || "",
  messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID || firebaseConfigDefault.messagingSenderId || "",
  appId: metaEnv.VITE_FIREBASE_APP_ID || firebaseConfigDefault.appId || "",
  measurementId: metaEnv.VITE_FIREBASE_MEASUREMENT_ID || firebaseConfigDefault.measurementId || ""
};

let app: any = null;
let auth: any = null;
let provider: any = null;
let initError: Error | null = null;

try {
  const isKeyEmpty = !firebaseConfig.apiKey || firebaseConfig.apiKey.trim() === "";
  const isKeyPlaceholder = firebaseConfig.apiKey.includes("YOUR_") || firebaseConfig.apiKey === "null" || firebaseConfig.apiKey === "undefined";
  
  if (isKeyEmpty || isKeyPlaceholder) {
    throw new Error('Firebase apiKey is missing or not configured. To enable Google Sign-In, please use "Set up Firebase" in the AI Studio UI or configure your Firebase environment variables.');
  }

  app = initializeApp(firebaseConfig);
  auth = getAuth(app);
  provider = new GoogleAuthProvider();
  // Request Google Docs and Google Drive scopes
  provider.addScope('https://www.googleapis.com/auth/documents');
  provider.addScope('https://www.googleapis.com/auth/drive');
} catch (err: any) {
  console.warn('Firebase or Auth initialization bypassed:', err.message || err);
  initError = err;
}

export { auth };

// Flag to indicate if we are in the middle of a sign-in flow.
let isSigningIn = false;
// Cache the access token in memory or load from localStorage
let cachedAccessToken: string | null = (() => {
  try {
    return localStorage.getItem('gdocs_access_token');
  } catch {
    return null;
  }
})();

// Initialize auth state listener. Call this on app load.
export const initAuth = (
  onAuthSuccess?: (user: User, token: string) => void,
  onAuthFailure?: () => void
) => {
  if (!auth || initError) {
    if (onAuthFailure) {
      setTimeout(() => onAuthFailure(), 0);
    }
    return () => {}; // return dummy unsubscriber
  }

  return onAuthStateChanged(auth, async (user: User | null) => {
    if (user) {
      // Try to reload token from localStorage if memory cached is null
      if (!cachedAccessToken) {
        try {
          cachedAccessToken = localStorage.getItem('gdocs_access_token');
        } catch (err) {
          console.error('[Auth] Failed to load access token from localStorage:', err);
        }
      }

      if (cachedAccessToken) {
        if (onAuthSuccess) onAuthSuccess(user, cachedAccessToken);
      } else if (!isSigningIn) {
        cachedAccessToken = null;
        if (onAuthFailure) onAuthFailure();
      }
    } else {
      cachedAccessToken = null;
      try {
        localStorage.removeItem('gdocs_access_token');
      } catch {}
      if (onAuthFailure) onAuthFailure();
    }
  });
};

// Must be called from a button click or user interaction
export const googleSignIn = async (): Promise<{ user: User; accessToken: string } | null> => {
  if (!auth || initError) {
    const errorMsg = initError ? initError.message : 'Firebase Auth is not configured. To make Google Sign-In work, click "Set up Firebase" in AI Studio or check your VITE_FIREBASE_API_KEY environment variable.';
    throw new Error(errorMsg);
  }
  try {
    isSigningIn = true;
    const result = await signInWithPopup(auth, provider);
    const credential = GoogleAuthProvider.credentialFromResult(result);
    if (!credential?.accessToken) {
      throw new Error('Failed to get access token from Firebase Auth');
    }

    cachedAccessToken = credential.accessToken;
    try {
      localStorage.setItem('gdocs_access_token', cachedAccessToken);
    } catch (e) {
      console.warn('Failed to save access token to localStorage:', e);
    }
    return { user: result.user, accessToken: cachedAccessToken };
  } catch (error: any) {
    console.error('Sign in error:', error);
    throw error;
  } finally {
    isSigningIn = false;
  }
};

export const getAccessToken = async (): Promise<string | null> => {
  if (!cachedAccessToken) {
    try {
      cachedAccessToken = localStorage.getItem('gdocs_access_token');
    } catch {}
  }
  return cachedAccessToken;
};

export const logout = async () => {
  try {
    localStorage.removeItem('gdocs_access_token');
  } catch {}
  cachedAccessToken = null;
  if (!auth) {
    return;
  }
  await auth.signOut();
};
